Fix export of button types + adjust disabled button styles
e2n/e2n-ui pull request #10
Opened 2024-06-10 07:37 UTC by sonjafeitsch

In diesem PR wurde der Export von den Button Types noch einmal angepasst, sodass die Types jetzt passen sollten. Zusätzlich habe ich die Styles von disabled Buttons angepasst.

2024-06-17 12:00 UTC, k-kaufmann requested changes
Sieht soweit gut aus 👍  ich würde die Typen nur noch etwas fester definieren

2024-06-17 12:00 UTC, k-kaufmann commented on src/components/Button/Button.tsx
> +  size?: 'default' | 'sm' | 'lg' | 'icon';
Gerade werden diese Typen doppelt definiert. 
Einmal hier und einmal implizit in Zeile 12 ff. Das gleiche gilt für die Varianten.
Hier würde ich Vorschlagen einmal die Typen zu definieren:
```typescript
type variants = 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link',
type sizes = 'default' | 'sm' | 'lg' | 'icon'
``` 

Anschließend einen Typ für die buttonVariants defienieren und dem cva mitgeben:
```typescript
type buttonVariants = {
    variant: Record<
      variants,
      string
    >;
    size: Record<sizes,string>;
  };
};

const buttonVariants = cva<buttonVariants>(
```

Und die Typen ebenfalls noch in den ButtonProps nutzen:
```typescript
export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  asChild?: boolean;
  size?: sizes
  variant?: variants
};
```

Dadurch können wir nicht an einer Stelle vergessen die Props zu erweitern sollten wir später eine Größe oder eine Variante hinzufügen.

2024-06-18 08:40 UTC, sonjafeitsch commented
@k-kaufmann Danke fürs Review 🙂 den Punkt mit dem Types finde ich gut und habe ich im Button und Switch so angepasst. Gerne nochmal drauf schauen

2024-06-18 09:10 UTC, k-kaufmann approved these changes
Sieht gut aus :+1:
Gut dass du es auch direkt beim Switch angepasst hast!

2024-06-18 09:13 UTC, merged