MV2-728 Combobox
e2n/e2n-ui pull request #19
Opened 2024-08-13 13:48 UTC by bluealf

Erstellen einer Comoboxkomponente, die aus Popover + Command Komponente besteht. Dazu kamen auch Dialog und Radio Group.

2024-08-16 07:51 UTC, k-kaufmann requested changes
Schaut im großen und ganzen schon echt solide aus 👍 
Folgende Punkte sind mir aber noch augefallen:
- Die Combobox hat einen transparenten Hintergrund => Dadurch sind Sachen Teilweise schwer lesbar, da die übereinander liegen. Gut zu erkennen auf der Documentation Seite für die Combobox

## Combo box Radio Group
- Ich kann Elemente nicht in einem öffnen aktivieren und wieder deaktivieren
- Wenn ich nur den Text anklicke aktiviert sich der kreis davor nicht
- Wenn ich Die Combobox öffne etwas auswähle. Sie wieder schließe und anschließend wieder öffne ist keines der Items als aktiv markiert.
- Ich kann mehrere Elemente auswählen, es wird aber in der Box nach dem schließen immer nur eines angezeigt. Brauchen wir hier wirklich eine mehrfach auswahl?

Und checkmal welche Yarn version der genommen hat :D die yarn.lock sieht zwar plausibel aus, daher denke ich es ist die richtige aber sicher ist sicher 1200 Zeilen sind schon happig 😅

2024-08-19 08:05 UTC, bluealf commented
Ich habe die mehrfach auswahl rausgehauen und geschaut dass es ungefähr so aussieht wie in der Vorlage. Bei der yarn.lock hoffe ich schaut es jetzt besser aus 😅

2024-08-20 09:16 UTC, k-kaufmann requested changes
Bis auf die anpassungen an der yarnrc siehts ganz gut aus

2024-08-20 09:16 UTC, k-kaufmann commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-4.1.0.cjs
Das bitte wieder rausnehmen.
Wir haben yarn nicht mit im Repo abgelegt.

2024-08-20 09:23 UTC, k-kaufmann requested changes
Mir sind noch ein par dinge aufgefallen ^^

2024-08-20 09:23 UTC, k-kaufmann commented on src/components/Combobox/Combobox.tsx
> +const frameworks = [
Die haben in der Combobox nix verloren.
Schließlich haben die nichts mit der eigentlichen funktion zu tun

2024-08-20 09:23 UTC, k-kaufmann commented on src/components/Combobox/Combobox.tsx
> +export function Combobox() {
Es müsste noch eine möglichkeit geben die Items, welche angezeigt werden sollen, zu Übergeben.

2024-08-20 09:23 UTC, k-kaufmann commented on src/components/Combobox/Combobox.tsx
> +              {frameworks.map((framework) => (
Das müsste Abhängig davon sein was in die Combobox hineingegeben wird

2024-08-20 09:23 UTC, k-kaufmann commented on src/components/Combobox/Combobox.stories.tsx
> +    <Popover open={open} onOpenChange={setOpen}>
Warum wird hierfür nicht die Combobox komponente verwendet?

2024-08-20 09:23 UTC, k-kaufmann commented on src/components/Combobox/Combobox.stories.tsx
> +      <Popover open={open} onOpenChange={setOpen}>
Warum wird hierfür nicht die Combobox komponente verwendet?

2024-08-22 13:42 UTC, k-kaufmann approved these changes
WIe besprochen noch die beiden Sachen Anpassen. Der Rest sieht gut aus 👍

2024-08-22 13:42 UTC, k-kaufmann commented on src/components/Combobox/Combobox.stories.tsx
> +        setOption={(currentValue) => {
Hier noch bitte onSelect als namen wählen

2024-08-22 13:42 UTC, k-kaufmann commented on src/components/Combobox/Combobox.tsx
> +                    setOpen(true);
Das ist überflüssig

2024-08-23 06:33 UTC, closed without merging