MV2-356: Button auf Shadcn umstellen
e2n/e2n-ui pull request #5
Opened 2024-05-06 10:48 UTC by sonjafeitsch

In diesem PR wurde die Button-Komponente auf Shadcn umgestellt. Bzgl dem Testen von Darkmode mit Tailwind in Storybook habe ich keine schöne Lösung gefunden, daher wird dieser Fall hier erst einmal nicht berücksichtigt. Das sollten wir uns noch einmal in einem separaten Ticket anschauen. @bluealf @k-kaufmann gerne mal drüberschauen und testen 🙂

2024-05-08 11:23 UTC, bluealf requested changes
Wenn der Name vom ButtonIcon angepasst ist, sollte es auch nicht mehr in den anderen Komponenten krachen und kann dann gemergt werden :)

2024-05-08 11:23 UTC, bluealf commented on src/components/Button/IconButton.tsx
> +export function ButtonIcon({ icon }: { icon: IconDefinition }) {
Die Datei heißt IconButton, die function aber ButtonIcon, aktuell verwenden wir IconButton, würde dass daher dabei belassen :)

2024-05-15 08:25 UTC, sonjafeitsch commented
@bluealf Deine Anmerkungen habe ich soweit angepasst und mich noch um den IconButton gekümmert. Gerne nochmal drüber schauen und testen 🙏

2024-05-15 08:37 UTC, bluealf requested changes
Der Button passt jetzt soweit, wenn ich aber yarn tsc --watch mache, kracht es bei mir noch bei der Tabellen, Drawer und Carousel Komponente, wegen der size property.

2024-05-17 07:36 UTC, sonjafeitsch commented
> Der Button passt jetzt soweit, wenn ich aber yarn tsc --watch mache, kracht es bei mir noch bei der Tabellen, Drawer und Carousel Komponente, wegen der size property.

Ah gut gesehen, daran habe ich tatsächlich nicht gedacht 🙈 ich schaue es mir nochmal an

2024-05-17 07:49 UTC, sonjafeitsch commented
@bluealf Ich habe die Fehler soweit gefixt, gerne nochmal drüber schauen ob es soweit passt 🙂

2024-05-17 08:20 UTC, bluealf approved these changes
Ich bekomme jetzt keine Fehler mehr, habe aber gesehen dass hier jetzt auch in fast allen Files aus einfachem Anführungszeichen durch den prettier doppeltes Anführungszeichen wurde, musst evtl. auch checken :)

2024-05-17 08:20 UTC, bluealf commented on src/components/Drawer/Drawer.tsx
> +  position?: "left" | "right";
Hier ist auch die Änderung durch den prettier, wurden vielleicht die Einstellungen mit einem VS Code Update zurückgesetzt 🤔

2024-05-17 08:20 UTC, bluealf commented on src/components/Drawer/Drawer.tsx
> +      left: position === "left" ? 0 : undefined,
Hier ebenso :)

2024-05-22 09:28 UTC, merged